### ISSUE TITLE
Add contact us mechanism from the main login page

### ISSUE THREAD

**Issue by megalodonatron** [qiime/qiime_web_app#201]

**Comment by adamrp** [comment]
What are we thinking for this?  We can't send people through fusebox to get to a nicely formatted "email us" page because header.psp will kick them back to index.psp since they are not logged in.  I think a simple mailto link may be the best in this case?  Or we could send them to a "email us" form that is _not_ nicely formatted through fusebox

**Comment by megalodonatron** [comment]
I just added a mailto link and pull req'd it

**Comment by adamrp** [comment]
I see that a pull request exists for exactly that -- good timing :)

**Comment by megalodonatron** [comment]
updated so that the email will now have subject AGLOGINHELP and body asking for kitID and other relevant information
