### ISSUE TITLE
Make HTML content not resizable.

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#375]
A few participants have reported that when they login they are not able to see the verification page or that they are only able to see the sidebar. I think this might be due to the behavior that the website has right now; where if the content doesn't fit the screen it will be re-sized, this often times seem to be causing a lot of confusion.

**Comment by ElDeveloper** [comment]
The following screenshot is an example:

![Captura de pantalla 2013-04-25 a la s 17 39 32](https://f.cloud.github.com/assets/375307/428265/713a42ec-ae01-11e2-9ac3-7f27908c1476.png)

Don't know what others think.

**Comment by douginator2000** [comment]
Those are the international shipping instructions - you have to have
clicked on the link to pull it up. It may be confusing because it opens in
a new window and doesn't have sample info in the sidebar.

On Thursday, April 25, 2013, Yoshiki Vázquez Baeza wrote:

> The following screenshot is an example:
> 
> [image: Captura de pantalla 2013-04-25 a la s 17 39 32]https://f.cloud.github.com/assets/375307/428265/713a42ec-ae01-11e2-9ac3-7f27908c1476.png
> 
> Don't know what others think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/375#issuecomment-17047495
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Plus the css is written so that it should just be one long column even if it's all smushed, I don't know what could be happening on their systems unless they're using some super old version of ie that is ignoring css rules.

![Screen Shot 2013-04-26 at 9 52 56 AM](https://f.cloud.github.com/assets/930642/431483/7fbae528-ae89-11e2-9007-49ad15b95cef.png)

**Comment by ElDeveloper** [comment]
I don't either and to be honest I don't understand what set of things lead you to only be able to see the sidebar on the left.

What I was thinking to alleviate this issue is to make the content of a restricted width so if people had smaller screens, then they could scroll. But that's just an idea.

Yoshiki.

**Comment by megalodonatron** [comment]
I played around with the css min-width attribute but using that really does make the content pop down to the bottom, where as using a % width should always keep it to the right of the menu.

**Comment by megalodonatron** [comment]
This is fixed.
