### ISSUE TITLE
Names with international characters create unexpected behaviors 

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#397]
Creating a new participant with the name `Döūgbert Sánchez` will be presented in the web portal as `D??gbert S?nchez`. The problem is presented when trying to remove this participant from the web interface, when clicking on the "remove participant" button, the web portal presents the right information but the user is never removed.

This issue is related to overally dealing with #395.

As per @douginator2000, he is getting this issue assigned.

**Comment by douginator2000** [comment]
I will make this top priority. For the moment, request that ppl stick to
the standard US set

On Wednesday, May 15, 2013, Yoshiki Vázquez Baeza wrote:

> Creating a new participant with the name Döūgbert Sánchez will be
> presented in the web portal as D??gbert S?nchez. The problem is presented
> when trying to remove this participant from the web interface, when
> clicking on the "remove participant" button, the web portal presents the
> right information but the user is never removed.
> 
> This issue is related to overally dealing with #395https://github.com/qiime/qiime_web_app/issues/395
> .
> 
> As per @douginator2000 https://github.com/douginator2000, he is getting
> this issue assigned.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/397
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Sure thing

**Comment by douginator2000** [comment]
So it's been a little tricky tracking down exactly at what level this is occurring. It does not appear to be a problem with the live database server (thebeast). It's character encoding is AL32UTF8 (SELECT \* FROM NLS_DATABASE_PARAMETERS;), which should (and does) support international character sets. Quarterbarrel has a different encoding listed - something we should rectify at some point. I believe the problem lies in the fact that the character columns for certain things (names, addresses, sample notes, etc...) need to be re-defined as nvarchar fields (double-byte character set), and beyond that the python code needs to be updated with appropriate encode/decode methods to actually display the characters properly. 

I was able to create a test scenario in which the additional characters show up properly on the website:

create table chartest
(
    name varchar2(200),
    nname nvarchar2(200)
);
insert into chartest (name, nname) values ('Döüg Wéñdęł', 'Döüg Wéñdęł');
commit;

Then, I added a test page on live under qiime/test/chartest.psp:

<%

from data_access_connections import data_access_factory
from enums import *
ag_data_access = data_access_factory(ServerConfig.data_access_type, 'american_gut')

query = "select \* from chartest"
results = ag_data_access.dynamicMetadataSelect(query)
for item in results:
    req.write(item[0].encode('utf8'))
    req.write('<br/>')
    x = item[1].encode('utf8')
    req.write(x)

%>

The output looks like this:

Doug We?del
Döüg Wéñdęł

The first scenario is pulling from a varchar2 field, second from the nvarchar2 field. Note that if encode is left off a python error is thrown when reading from the nvarchar2 field.

Solution will probably be to convert these fields to nvarchar2 and adjust all read/write references to those fields in python. 

I was not able to reproduce this on my virtual box instance (i.e., I always get "?" for all international characters regardless of encoding) even when connected to the production database. This makes me think the encoding problem is related to the OS or python configuration but I haven't been able to track it down that far yet.

**Comment by adamrp** [comment]
Just talking with Yoshiki about this, and we propose just making sure that all text boxes accept only [a-zA-Z0-9](except of course numeric text boxes).  We can do this in JS.  Will we really be losing anything by making these restrictions?  If a participant is entering information using other symbols, then it's unlikely we can even understand that information or, even if we could understand it, we would probably be able to understand it without any additional accents/special markings/etc.

**Comment by adamrp** [comment]
well, that was some weird formatting.  Anyways, it's supposed to say restrict it to capital and lowercase letters and numbers, except numeric textboxes which will be only numbers and possibly decimals.

Adam

**Comment by RNAer** [comment]
symbols such as "-" should be probably allowed? Also, just not to confuse users, it would be great to prompt a message saying something like "only alphanumeric letters are allowed" when users try to type illegal characters?

**Comment by ElDeveloper** [comment]
Yes that is a good idea +1

**Comment by adamrp** [comment]
:+1:   We could also potentially allow single quotes (making sure to replace them with two single quotes before sending to the DB), but I'm not sure it's worth the trouble.  How about just alphanumerics, dots (.), and hyphens (-)?

**Comment by douginator2000** [comment]
Sure, that works for me too - agree with the restrictions.

On Thu, Jun 20, 2013 at 10:25 AM, adamrp notifications@github.com wrote:

> [image: :+1:] We could also potentially allow single quotes (making sure
> to replace them with two single quotes before sending to the DB), but I'm
> not sure it's worth the trouble. How about just alphanumerics, dots (.),
> and hyphens (-)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/397#issuecomment-19764544
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by adamrp** [comment]
Previously, the same function was being used to validate text for names and email addresses.  This will no longer work (and was probably not a great idea in the first place).  Looked up format of valid email addresses, turns out to be super complicated.  Easiest way is probably to send user a confirmation email and have them click a link... I dont like it, but I dont know what else to do...
