### ISSUE TITLE
Add descriptive checkboxes to barcode scanner utility

### ISSUE THREAD

**Issue by ElDeveloper** [qiime/qiime_web_app#446]
@RNAer and I should begin working on this and talk with the team that handles the samples as they arrive to the lab so we can get a good grip of what are the things that need to be checked.

---

Initial suggestions are:
- Sample is overloaded checkbox.
- Sample has noticeable growing mold.

**Comment by douginator2000** [comment]
I added a bunch of notes to the "master" barcode scanner utility as well:

#298 

https://github.com/qiime/qiime_web_app/issues/298?source=cc

I'll let the Git master decide how he wants to handle the task breakout.

On Mon, Jun 24, 2013 at 12:04 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> @RNAer https://github.com/RNAer and I should begin working on this and
> talk with the team that handles the samples as they arrive to the lab so we
> 
> ## can get a good grip of what are the things that need to be checked.
> 
> Initial suggestions are:
> - Sample is overloaded checkbox.
> - Sample has noticeable growing mold.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/446
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Thanks @douginator2000!

**Comment by RNAer** [comment]
a side question just popped into my mind - why do we use barcode instead of
QR code? as far as I know, QR code is more convenient, storing more info
and more robust to dirt/damages.

**Comment by douginator2000** [comment]
Mostly because the physical sample tubes are curved and QR codes are square
- hard to scan.

On Mon, Jun 24, 2013 at 12:49 PM, Zech Xu notifications@github.com wrote:

> a side question just popped into my mind - why do we use barcode instead
> of
> QR code? as far as I know, QR code is more convenient, storing more info
> and more robust to dirt/damages.
> 
> On Mon, Jun 24, 2013 at 12:43 PM, Yoshiki Vázquez Baeza <
> notifications@github.com> wrote:
> 
> > Thanks @douginator2000 https://github.com/douginator2000!
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/issues/446#issuecomment-19926886>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/446#issuecomment-19927197
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Yes agreed adding the level of complexity that is implies using QR codes is (I think) not worth it.

If you are really curious about this, look at this mathematica question @ stack exchange

http://mathematica.stackexchange.com/questions/26268/qr-code-in-shopping-cart-handle

**Comment by wasade** [comment]
@RNAer, I tested QR codes early on. The curvature was an issue, and
printing codes small enough so that it the curvature was a non-issue
introduced problems in reliably scanning the images. Same for placing the
codes on the tops of the tubes.

**Comment by RNAer** [comment]
thanks!

**Comment by RNAer** [comment]
@douginator2000 , could you add moldy and overloaded column to the barcode table? I will put the psp page (including the enhancements in the other ticket) in place.

**Comment by douginator2000** [comment]
I can add additional columns - but let's sort out the full list of
additional columns that need to be added first (I suspect there will be
more than just those two, e.g. a notes field and possibly others too). Can
you start an email thread to me, Daniel, Kris, Yoshiki, Adam, and anyone
else you want to rope in so that we can figure out all of the fields?
Thanks!

On Tue, Jun 25, 2013 at 1:54 PM, Zech Xu notifications@github.com wrote:

> @douginator2000 https://github.com/douginator2000 , could you add moldy
> and overloaded column to the barcode table? I will put the psp page in
> place.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/446#issuecomment-20002454
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by RNAer** [comment]
It's done. you can play around it - it's on the webdav. Now the barcode
util allows:
1. show the current barcode info
2. update current barcode info into database, including moldy, overloaded,
other issues and free text notes, date info
3. auto email users and/or participant about their sample status
4. alert if barcode is invalid
...

it should work for barcode in any combinations of verified and assigned
status. let me know if there is any problem; otherwise I will issue a pull
request. The only thing left to do is to use jquery datepicker for date
input.  hope to get it done tomorrow. But it's quite useable even without
it.

**Comment by douginator2000** [comment]
That's great, thank you Zech! Please do add the date picker control. I'll
play around with it today.

On Thursday, June 27, 2013, Zech Xu wrote:

> It's done. you can play around it - it's on the webdav. Now the barcode
> util allows:
> 1. show the current barcode info
> 2. update current barcode info into database, including moldy, overloaded,
> other issues and free text notes, date info
> 3. auto email users and/or participant about their sample status
> 4. alert if barcode is invalid
> ...
> 
> it should work for barcode in any combinations of verified and assigned
> status. let me know if there is any problem; otherwise I will issue a pull
> request. The only thing left to do is to use jquery datepicker for date
> input. hope to get it done tomorrow. But it's quite useable even without
> it.
> 
> On Tue, Jun 25, 2013 at 2:12 PM, Doug Wendel <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>wrote:
> 
> > I can add additional columns - but let's sort out the full list of
> > additional columns that need to be added first (I suspect there will be
> > more than just those two, e.g. a notes field and possibly others too).
> > Can
> > you start an email thread to me, Daniel, Kris, Yoshiki, Adam, and anyone
> > else you want to rope in so that we can figure out all of the fields?
> > Thanks!
> > 
> > On Tue, Jun 25, 2013 at 1:54 PM, Zech Xu <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>
> > 
> > wrote:
> > 
> > > @douginator2000 https://github.com/douginator2000 , could you add
> > > moldy
> > > and overloaded column to the barcode table? I will put the psp page in
> > > place.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/issues/446#issuecomment-20002454>
> > > 
> > > .
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edu <javascript:_e({}, 'cvml', 'wendel@colorado.edu');>
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/issues/446#issuecomment-20003644>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/446#issuecomment-20170566
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
This issue was closed a while ago by @RNAer in #448
