### ISSUE TITLE
qiime db is not sending activation emails

### ISSUE THREAD

**Issue by wasade** [qiime/qiime_web_app#645]
So new users cannot register

**Comment by adamrp** [comment]
@wasade I think it actually is, right? This turned out not to be an issue?

**Comment by wasade** [comment]
It could have been an instance where the users email server was filtering

**Comment by adamrp** [comment]
Yeah, I think that's what he said was happening, since he tried with a different email address and it worked correctly.  Or perhaps he mis-typed his email address on the registration page.  If the latter is the case, we _could_ have people enter their email address twice to help confirm the spelling, but I'm not sure it's necessary.  If you want to add another text box on the registration page for "please type email again", then we can create another issue for it, but I'm closing this one since the site is actually sending activation emails.
